### ISSUE TITLE
Add package:lib-caffe-intel-request-cpu

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck-request-asplos18-caffe-intel#2]
The actual ReQuEST artifact uses a special branch: https://github.com/intel/caffe/tree/request_artifact (91 commits ahead of the master right now).

**Comment by psyhtest** [comment]
[Committed](https://github.com/dividiti/ck-caffe/commit/a26db0a03504c7457c2d5c8155b75f3111e940bc) a copy of `package:lib-caffe-intel-master-cpu`, with Windows support removed.

It fails to build with GCC 6.3, however, due to:
```
/home/anton/CK_TOOLS/lib-caffe-intel-request-cpu-trunk-gcc-6.3.0-linux-64/src/src/caffe/layer_factory.cpp: In instantiation of ‘boost::shared_ptr<caffe::Layer<Dtype> > caffe::GetConvolutionLayer(const caffe::LayerParameter&) [with Dtype = float]’:
/home/anton/CK_TOOLS/lib-caffe-intel-request-cpu-trunk-gcc-6.3.0-linux-64/src/src/caffe/layer_factory.cpp:161:1:   required from here
/home/anton/CK_TOOLS/lib-caffe-intel-request-cpu-trunk-gcc-6.3.0-linux-64/src/src/caffe/layer_factory.cpp:92:8: error: variable ‘use_dilation’ set but not used [-Werror=unused-but-set-variable]
   bool use_dilation = false;
        ^~~~~~~~~~~~
```
I'll see if I can introduce a patch...

**Comment by psyhtest** [comment]
OK, another error now:
```
/home/anton/CK_TOOLS/lib-caffe-intel-request-cpu-trunk-gcc-6.3.0-linux-64/src/src/caffe/layers/mkldnn_inner_product_layer.cpp: In member function ‘void caffe::MKLDNNInnerProductLayer<Dtype>::InitInnerProductBwd(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&)’:
/home/anton/CK_TOOLS/lib-caffe-intel-request-cpu-trunk-gcc-6.3.0-linux-64/src/src/caffe/layers/mkldnn_inner_product_layer.cpp:357:2: error: this ‘else’ clause does not guard... [-Werror=misleading-indentation]
  else
  ^~~~
/home/anton/CK_TOOLS/lib-caffe-intel-request-cpu-trunk-gcc-6.3.0-linux-64/src/src/caffe/layers/mkldnn_inner_product_layer.cpp:361:5: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘else’
     ipBwdData_desc.reset(new inner_product_backward_data::desc(init_bottom_md, init_weights_md, init_top_md));
     ^~~~~~~~~~~~~~
```

**Comment by psyhtest** [comment]
So, the following patches need to be applied:
```
diff --git a/src/caffe/layer_factory.cpp b/src/caffe/layer_factory.cpp
index 0218d96..e040da2 100644
--- a/src/caffe/layer_factory.cpp
+++ b/src/caffe/layer_factory.cpp
@@ -116,7 +116,8 @@ shared_ptr<Layer<Dtype> > GetConvolutionLayer(
     }
 #endif
 #ifdef MKLDNN_SUPPORTED
-    else if (ep.isEngine("MKLDNN")) {
+    // NB: Only read 'use_dilation' to silence '-Werror=unused-but-set-variable'.
+    else if (ep.isEngine("MKLDNN") || use_dilation) {
       engine = ConvolutionParameter_Engine_MKLDNN;
     }
 #endif
diff --git a/src/caffe/layers/mkldnn_inner_product_layer.cpp b/src/caffe/layers/mkldnn_inner_product_layer.cpp
index 9994df7..501ac67 100644
--- a/src/caffe/layers/mkldnn_inner_product_layer.cpp
+++ b/src/caffe/layers/mkldnn_inner_product_layer.cpp
@@ -351,11 +351,12 @@ void MKLDNNInnerProductLayer<Dtype>::InitInnerProductBwd(const vector<Blob<Dtype
     // Initialize inner_product primitive descriptor
     shared_ptr<inner_product_backward_data::desc> ipBwdData_desc;
     shared_ptr<inner_product_backward_weights::desc> ipBwdWeights_desc;
- if (this->bias_term_)
-    ipBwdWeights_desc.reset(new inner_product_backward_weights::desc(init_bottom_md, init_weights_md
+    // NB: Fix identation to silence '-Werror=misleading-indentation'.
+    if (this->bias_term_)
+      ipBwdWeights_desc.reset(new inner_product_backward_weights::desc(init_bottom_md, init_weights_md
                         , init_bias_md, init_top_md));
- else
-    ipBwdWeights_desc.reset(new inner_product_backward_weights::desc(init_bottom_md, init_weights_md
+    else
+      ipBwdWeights_desc.reset(new inner_product_backward_weights::desc(init_bottom_md, init_weights_md
                         , init_top_md));
 
     ipBwdData_desc.reset(new inner_product_backward_data::desc(init_bottom_md, init_weights_md, init_top_md));
```

**Comment by psyhtest** [comment]
It's curious that Caffe built with this `request_artifact` branch doesn't [complain](https://github.com/ctuning/ck-request-asplos18-caffe-intel/issues/1#issuecomment-365915100) about ` libmkldnn.so.0`, like the `master` does...
 
```
$ find ~/CK_TOOLS/lib-caffe-intel-request-cpu-trunk-gcc-6.3.0-linux-64/src -name libmkldnn.so.0
/home/anton/CK_TOOLS/lib-caffe-intel-request-cpu-trunk-gcc-6.3.0-linux-64/src/external/mkldnn/install/lib/libmkldnn.so.0
/home/anton/CK_TOOLS/lib-caffe-intel-request-cpu-trunk-gcc-6.3.0-linux-64/src/external/mkldnn/build/src/libmkldnn.so.0
```

**Comment by psyhtest** [comment]
It exhibits [similar](https://github.com/ctuning/ck-request-asplos18-caffe-intel/issues/1#issuecomment-365923784) performance issues, however, when setting `OMP_NUM_THREADS` explicitly:
```
$ ck run program:caffe --cmd_key=time_cpu --env.CK_CAFFE_BATCH_SIZE=1
...
  "post_processed": "yes", 
  "time_bw_ms": 18.925, 
  "time_bw_s": 0.018925, 
  "time_fw_ms": 23.875, 
  "time_fw_s": 0.023875, 
  "time_fwbw_ms": 43.0, 
  "time_fwbw_s": 0.043000000000000003, 
  "time_total_ms": 43.0, 
  "time_total_ms_kernel_0": 43.0, 
  "time_total_s": 0.043000000000000003, 
  "time_total_s_kernel_0": 0.043000000000000003
}

$ ck run program:caffe --cmd_key=time_cpu --env.CK_CAFFE_BATCH_SIZE=1 \
--env.OMP_NUM_THREADS=20
...
  "post_processed": "yes", 
  "time_bw_ms": 3981.07, 
  "time_bw_s": 3.9810700000000003, 
  "time_fw_ms": 2480.39, 
  "time_fw_s": 2.48039, 
  "time_fwbw_ms": 6462.0, 
  "time_fwbw_s": 6.462, 
  "time_total_ms": 6462.0, 
  "time_total_ms_kernel_0": 6462.0, 
  "time_total_s": 6.462, 
  "time_total_s_kernel_0": 6.462
}
```

**Comment by psyhtest** [comment]
As the package installation works, however, I'll close this issue, and keep investigating in #1 ...
